# Site
name: 'Brooke K. Ryan'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/brooke_ghostie.png'
baseurl: ''
disqus: 'brookekryan'
email: 'brookekelseyryan@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

teaching:
  information-retrieval:
    name:           Information Retrieval
    site:           https://www.brookekryan.com
    avatar:         /assets/images/brooke_avatar.jpg
    description:    "An introduction to information retrieval including indexing, retrieval, classifying and clustering text and multimedia documents."
    role:           teaching assistant
    number:         CS-141

authors:
    brooke:
      name:           Brooke Ryan
      site:           https://www.brookekryan.com
      avatar:         /assets/images/brooke_avatar.jpg
      bio:            "I'm a writer and graduate student in Computer Science at UC Irvine."
      email:          brooke.ryan@uci.edu

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]