# Site
name: 'PROBLEMON'
description: 'Comparte tu opinión con miles de personas.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'hola@problemon.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
  # TODO: Replace deafult author
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      permalink: /posts/:path

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all authors
  - scope:
      path: "_authors"
    values:
      layout: author

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# collections
collections:
  authors:
    output: true
    permalink: /author/:path

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
