# Site
name: 'SpellOnYou'
description: "Be afraid only of standing still. Remain fresh, body and soul."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'dionne'
email: 'kimjiwon08@snu.ac.kr'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:year/:month/:title/

twitter_username: karma_Aleph
# github_username:  SpellOnYou
# disqus_shortname: dionne
# favicon:     "/images/favicon.ico"
# aboutme: In the face of ambiguity, refuse the temptation to guess.
# aboutme_photo: "/images/IMG_0610.JPG"

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# assets/images/my_photo.png
authors:
    sal:
      name:           dionne
      site:           https://spellonyou.github.io
      avatar:         /assets/images/my_photo.png
      bio:            "Welcome, I'm dionne.? I hope you enjoy my articles!"
      email:          kimjiwon08@snu.ac.kr
      twitter:        https://twitter.com/karma_Aleph

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Dionne
      avatar: assets/images/my_photo.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]