# Site
name: "Bitcoin Sozial"
description: "Kollektiv für soziale Fragen im Zeitalter von Bitcoin"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "xxx"
email: "bitcoinsozial@protonmail.com"
url: "https://bitcoinsozial.de"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include:
  - _pages
  - .well-known
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-twitter-plugin

authors:
  bitcoinsozial:
    name: Bitcoin Sozial
    site: https://www.bitcoinsozial.de/
    avatar: assets/images/logo.jpg
    bio: "Kollektiv für soziale Fragen im Zeitalter von Bitcoin"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/bitcoinsozial

  calle:
    name: Calle B.
    # site: https://www.wowthemes.net
    avatar: assets/images/authors/avatar_calle.jpg
    bio: "Wissenschaftler und Open-Source Hacker."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/callebtc

  lola:
    name: L0la L33tz
    # site: https://www.wowthemes.net
    avatar: assets/images/authors/avatar_lola.jpg
    bio: "Unbeabsichtigte Kryptoanarchistin."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/L0laL33tz

  btctheory:
    name: Bitcoin Theory
    site: https://btctheory.com/
    avatar: assets/images/authors/avatar_btctheory.jpg
    bio: "Bitcoiner, Anarchist und Philosoph."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/BTCtheory

  troycross:
    name: Troy Cross
    # site: https://btctheory.com/
    avatar: assets/images/authors/avatar_troycross.jpg
    bio: "Philosoph. Umweltaktivist. Bitcoiner."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/thetrocro

  resistancemoney:
    name: Resistance Money
    site: http://resistance.money/
    avatar: assets/images/authors/avatar_resistancemoney.jpg
    bio: "Ein Bitcoin Forschungskollektiv mit Andrew M. Bailey (Yale-NUS College), Bradley Rettler (University of Wyoming) aus Craig Warmke (Northern Illinois University)"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/resistancemoney

  bitcoinersforfuture:
    name: Stephan (Bitcoiners for Future)
    # site: http://resistance.money/
    avatar: assets/images/authors/avatar_bitcoinersforfuture.jpg
    bio: "We may not have a planet B, but we have a plan ₿."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/BTCersforfuture

  phil:
    name: Phil
    # site: http://resistance.money/
    avatar: assets/images/authors/avatar_phil.jpg
    bio: "Schreibt gegen häufige Irrtümer über Bitcoin."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/OfBehodler

  tommaxwell:
    name: Tom Maxwell
    site: https://tomjmaxwell.medium.com/
    avatar: assets/images/authors/avatar_tommaxwell.jpg
    bio: "Liberty, Equality, Solidarity"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/tomjmaxwell

  weezel:
    name: Weezel
    # site: https://tomjmaxwell.medium.com/
    avatar: assets/images/authors/avatar_weezel.jpg
    bio: "Scientific Bitcoin enthusiast"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/magicolen

  vitalik:
    name: Vitalik Buterin
    site: https://vitalik.ca/
    avatar: assets/images/authors/avatar_vitalik.jpg
    bio: "Gründer von Ethereum"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/VitalikButerin

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: calle
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
