# Site
name: "Bitcoin Sozial"
description: "Kollektiv für Soziale Fragen im Zeitalter von Bitcoin"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "xxx"
email: "bitcoinsozial@protonmail.com"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

authors:
  calle:
    name: Calle B.
    # site: https://www.wowthemes.net
    avatar: assets/images/authors/avatar_calle.jpg
    bio: "Wissenschaftler und Open-Source Hacker, der freie Bitcoin Software baut"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/callebtc

  lola:
    name: L0la L33tz
    # site: https://www.wowthemes.net
    avatar: assets/images/authors/avatar_lola.jpg
    bio: "Accidental Cryptoanarchist"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/L0laL33tz

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: calle
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
