# Site
name: 'Tolga Altaş'
description: 'Kişisel günceleme alanı.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicontolga.png'
baseurl: '/'
disqus: 'tolgaaltas'
email: 'info@tolgaaltas.com'
mailchimp-list: 'https://tolgaaltas.us8.list-manage.com/subscribe/post?u=f466b0644dff94a7d92722e31&amp;id=87a6d466a0'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Tolga Altaş
      site:           https://tolgaaltas.com
      avatar:         /assets/images/taltas.jpg
      bio:            "I don't know what I'm doing but I'm going to figure it out."
      email:          info@tolgaaltas.com
      twitter:        https://twitter.com/tolgaaaltas
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/taltas.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
