# Site
name: "Bitcoin Sozial"
description: "Kollektiv für soziale Fragen im Zeitalter von Bitcoin"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "xxx"
email: "bitcoinsozial@protonmail.com"
url: "https://bitcoinsozial.de"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-twitter-plugin

authors:
  calle:
    name: Calle B.
    # site: https://www.wowthemes.net
    avatar: assets/images/authors/avatar_calle.jpg
    bio: "Wissenschaftler und Open-Source Hacker."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/callebtc

  lola:
    name: L0la L33tz
    # site: https://www.wowthemes.net
    avatar: assets/images/authors/avatar_lola.jpg
    bio: "Unbeabsichtigte Kryptoanarchistin."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/L0laL33tz

  btctheory:
    name: Bitcoin Theory
    site: https://btctheory.com/
    avatar: assets/images/authors/avatar_btctheory.jpg
    bio: "Bitcoiner, Anarchist und Philosoph."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/BTCtheory

  troycross:
    name: Troy Cross
    # site: https://btctheory.com/
    avatar: assets/images/authors/avatar_troycross.jpg
    bio: "Philosoph. Umweltaktivist. Bitcoiner."
    # email: fakemail@gmail.com
    twitter: https://twitter.com/thetrocro

  resistancemoney:
    name: Resistance Money
    site: http://resistance.money/
    avatar: assets/images/authors/avatar_resistancemoney.jpg
    bio: "Ein Bitcoin Forschungskollektiv. Andrew M. Bailey (Yale-NUS College), Bradley Rettler (University of Wyoming), Craig Warmke (Northern Illinois University)"
    # email: fakemail@gmail.com
    twitter: https://twitter.com/resistancemoney

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: calle
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
