# Site
name: 'Around-AI'
description: 'Những điều thú vị xung quanh AI'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
domain: around-ai.com
email: 'thuc248997@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    thuc:
      name:           Thuc
      site:           https://www.around-ai.com
      avatar:         /assets/images/avatar2.jpg
      bio:            "Xin chào. Mình là Thức. Mình là tác giả chính của trang này. Blog của mình hiện tại chủ yếu viết về chủ đề xoay quanh Artificial intelligence(AI)."
      email:          thuc248997@gmail.com
      twitter:        https://twitter.com/thuc248997
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Thuc
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
mathjax: true
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]