# Site
name: 'Tidbits'
description: 'My own space'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'tid-bits'
email: 'nour.hashem95@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
title : "Tidbits"
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Noor:
      name:           Noor
      site:           https://github.com/noorhashem
      avatar:         assets/images/avatar1.jpg
      bio:            "A Software mobile app developer with a knack for AI & Computer Vision. I like to build edgy “handy” solutions to a problem and brew some cool techy stuff in my secret lab. I have multiple interests that won't fit in a short bio, but I'd be ranting about those here besides my coding blogposts"
      email:          nour.hashem95@gmail.com
      twitter:        https://twitter.com/noorhashem
     

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Noor
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
