name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - name: Bundler Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install libvips via apt
        if: runner.os == 'Linux'
        run: |
          # sudo -E apt-get update -qq -o Acquire::Retries=3
          sudo -E apt-get install -y libvips42
          echo "I PRINT THE PATH BRO"
          echo $LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/:/usr/lib/:/usr/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
          echo "I PRINT THE PATH BRO"
          echo $LD_LIBRARY_PATH
          echo "/lib/x86_64-linux-gnu"
          sudo ls /lib/x86_64-linux-gnu
          echo "/usr/local"
          sudo ls /usr/local
          echo "/usr/lib"
          sudo ls /usr/lib
          # echo "LDCONFIG"
          # sudo ldconfig -v
          echo "LD_LIBRARY_PATH=/usr/local/lib/:/usr/lib/:/usr/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/" >> $GITHUB_ENV
      - name: Echo
        run: echo $LD_LIBRARY_PATH
      - name: Build & Deploy to GitHub Pages
        uses: joshlarsen/jekyll4-deploy-gh-pages@master
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      # - name: Build & Deploy to GitHub Pages
      #   uses: jeffreytse/jekyll-deploy-action@master
      #   with:
      #     provider: "github"
      #     token: ${{ secrets.GITHUB_TOKEN }}
